### ISSUE TITLE
FI compilation fails

### ISSUE THREAD

**Issue by mkoivi-ms** [synthetichealth/synthea-international#12]
FI module installation fails according to instructions fails immediately to compilation error:

AppTest > testApp FAILED
    java.lang.ExceptionInInitializerError
        at org.mitre.synthea.world.geography.Location.<init>(Location.java:102)
        at org.mitre.synthea.engine.Generator.init(Generator.java:226)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:209)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:186)
        at App.main(App.java:227)
        at AppTest.testApp(AppTest.java:46)

        Caused by:
        java.lang.Exception: The city Bedford was not found in the demographics file.
            at org.mitre.synthea.world.geography.Location.<init>(Location.java:75)
            ... 5 more

**Comment by jawalonoski** [comment]
You probably need to change `src/test/resources/test.properties` to point at a [location in FI](https://github.com/synthetichealth/synthea-international/blob/master/fi/src/main/resources/geography/demographics.csv).

Here is what Synthea normally contains:

https://github.com/synthetichealth/synthea/blob/d2e98b2a5353e4fb51e63074f06158f9a4c77b41/src/test/resources/test.properties#L10-L14

Here is what the FI file shows now:

https://github.com/synthetichealth/synthea-international/blob/a3143159f7e1bb2f5813ad6a0f190a02934c9c1a/fi/test/main/resources/test.properties#L1-L5

It should probably be something like this (or whatever you want, picking locations from the [FI demographics file](https://github.com/synthetichealth/synthea-international/blob/master/fi/src/main/resources/geography/demographics.csv)):

```properties
test_state.default = Uusimaa
test_state.alternative = Pirkanmaa


test_town.default = Helsinki
test_town.alternative = Tampere
```

**Comment by jawalonoski** [comment]
Let me know if that fixes it. Happy to take a pull request if that works.

**Comment by jawalonoski** [comment]
In general, it may help to read this series of "Other Areas" articles on the main Synthea wiki to help troubleshoot. https://github.com/synthetichealth/synthea/wiki/Other-Areas

We may also need to update the instructions for Finland in particular, or Synthea International in general. Happy to have suggestions if you find they are incorrect.
