### ISSUE TITLE
Compatibility With Synthea Versions & Issue

### ISSUE THREAD

**Issue by Ryan-nd** [synthetichealth/synthea-international#17]
Hello,

Just wanted to ask  about configuring the data to New Zealand, I'm using Synthea version 3.1.1 and I've manually imported the geography ,Payers & Provider from the NZ files provided. Wondering is it  because programme requires Synthea Version 3.0.0, as in Synthea 3.1.1, the code  has ' fipscodes'. while in Synthea 3.0.0 does not. For the foreign_birthplace, would I have to make changes to the data by adding in a New Zealand in as well as New Zealand is not included inside the original foreign_birthplace file.  Would apprecaite any insights on that.

Regards,
Ryan Li

**Comment by bobvanderlinden** [comment]
Same problem for The Netherlands. Solved a number of the errors coming out of Synthea, but eventually gave up. The current international setup doesn't seem maintainable in the long run.

**Comment by jawalonoski** [comment]
We have a small team, and we do not currently test every ancillary project with each new Synthea change -- we just don't have the bandwidth. Maybe someone on the core team can find some time and see if the fixes are easy for us to make. Ideally, someone from the community with interest in these configurations would update them and submit a PR.

**Comment by martinhinze** [comment]
Hello, I just tried to use the German version of Synthea International and apparently also ran into compatibility issues. Synthea International is at this moment apparently not working with the current version of Synthea, right?
This is the error message when running `./run_synthea -p [N]`:
```
> Task :run FAILED
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because the return value of "org.mitre.synthea.world.geography.Location.getAbbreviation(String)" is null
        at org.mitre.synthea.world.agents.PayerManager.loadPayers(PayerManager.java:137)
        at org.mitre.synthea.world.agents.PayerManager.loadPayers(PayerManager.java:107)
        at org.mitre.synthea.engine.Generator.init(Generator.java:265)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:209)
        at App.main(App.java:270)
```

**Comment by jawalonoski** [comment]
@martinhinze Correct, it is not currently working. It will probably take a little bit of effort to make corrections to the Synthea International files to make them functional with the latest version of Synthea.

**Comment by samielsabri** [comment]
Sorry to revive this thread, but which version of Synthea is compatible with international? I tried to make Canadian demographic data work for a while now and then stumbled across this.
