### ISSUE TITLE
NullPointerException: Cannot invoke String.toUpperCase()

### ISSUE THREAD

**Issue by linforestzhang** [synthetichealth/synthea-international#19]
Copy synthea-international-master\\fi\\* to my local synthea-3.3.0

CMD:
run_synthea.bat -p 1

CMD Console Output:
`
ARG = -p
ARG = 1
ARG =
syntheaArgs =  '-p','1',

> Task :run FAILED
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because the return value of "org.mitre.synthea.world.geography.Location.getAbbreviation(String)" is null
        at org.mitre.synthea.world.agents.PayerManager.loadPayers(PayerManager.java:137)
        at org.mitre.synthea.world.agents.PayerManager.loadPayers(PayerManager.java:107)
        at org.mitre.synthea.engine.Generator.init(Generator.java:265)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:209)
        at App.main(App.java:274)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '...\jdk-17.0.7+7\bin\java.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 2s
4 actionable tasks: 3 executed, 1 up-to-date
`

**Comment by jawalonoski** [comment]
Yes, many of these configurations are broken with the latest version of Synthea. A `fixes` branch is in progress, but the priority is low, so it might take a while to fix all of them.

**Comment by linforestzhang** [comment]
Got it.  Thank you so much, Jason.  And looking forward to it.

**Comment by pmedvedev** [comment]
Is there a recommended previous version to fall back to? I believe the question I posted here: https://github.com/synthetichealth/synthea-international/pull/8#issuecomment-2506831269 is around the same issue I'm having.

**Comment by Zachary-Higgins-Altera** [comment]
Not sure if anyone is monitoring this repo, but if you could share which version this project supports, I think that would be really helpful. 

v2.5.0 doesn't seem to work.

**Comment by jawalonoski** [comment]
> Not sure if anyone is monitoring this repo, but if you could share which version this project supports, I think that would be really helpful.
> 
> v2.5.0 doesn't seem to work.

See https://github.com/synthetichealth/synthea-international/pull/20 and checkout the `fixes` branch.

**Comment by Zachary-Higgins-Altera** [comment]
Thanks @jawalonoski 
That branch works for Canada. I didn't realize I had to specify the providence. Admittedly I had the luxury of taking the inner workings for granted until today. The fixes branch worked as long as I specified the providence as a separate arg.

**Comment by NeuroinformaticaFBF** [comment]
> Thanks [@jawalonoski](https://github.com/jawalonoski) That branch works for Canada. I didn't realize I had to specify the providence. Admittedly I had the luxury of taking the inner workings for granted until today. The fixes branch worked as long as I specified the providence as a separate arg.

So, how did you manage to make the Canada work?
Pull, checkout to branch `international_update`, copy Canada files, and run it?
I can't seem to find the correct order of operations

Thanks!
